export const RESET_DATA = "RESET_DATA";
export const ADD_PLAYER = "ADD_PLAYER";
export const TOGGLE_PLAYER_FROZEN = "TOGGLE_PLAYER_FROZEN";
export const ADD_GAME_TO_PLAYER = "ADD_GAME_TO_PLAYER";
export const ADD_WIN_TO_PLAYER = "ADD_WIN_TO_PLAYER";
export const ADD_LOSS_TO_PLAYER = "ADD_LOSS_TO_PLAYER";
