export const RESET_PLAYER_DATA = "RESET_PLAYER_DATA";
export const ADD_PLAYER = "ADD_PLAYER";
export const TOGGLE_PLAYER_FROZEN = "TOGGLE_PLAYER_FROZEN";
export const ADD_WIN_TO_PLAYER = "ADD_WIN_TO_PLAYER";
export const ADD_LOSS_TO_PLAYER = "ADD_LOSS_TO_PLAYER";
export const UPDATE_RELATIVE_STATS_FOR_PLAYERS =
  "UPDATE_RELATIVE_STATS_FOR_PLAYERS";
